// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zalando.komang.protobuf.Events



@SerialVersionUID(0L)
final case class ApplicationCreated(
    application: scala.Option[com.zalando.komang.protobuf.Events.Application] = None
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[ApplicationCreated] with com.trueaccord.lenses.Updatable[ApplicationCreated] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (application.isDefined) { __size += 1 + com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(application.get.serializedSize) + application.get.serializedSize }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: com.google.protobuf.CodedOutputStream): Unit = {
      application.foreach { __v =>
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__v.serializedSize)
        __v.writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: com.google.protobuf.CodedInputStream): com.zalando.komang.protobuf.Events.ApplicationCreated = {
      var __application = this.application
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __application = Some(com.trueaccord.scalapb.LiteParser.readMessage(_input__, __application.getOrElse(com.zalando.komang.protobuf.Events.Application.defaultInstance)))
          case tag => _input__.skipField(tag)
        }
      }
      com.zalando.komang.protobuf.Events.ApplicationCreated(
          application = __application
      )
    }
    def getApplication: com.zalando.komang.protobuf.Events.Application = application.getOrElse(com.zalando.komang.protobuf.Events.Application.defaultInstance)
    def clearApplication: ApplicationCreated = copy(application = None)
    def withApplication(__v: com.zalando.komang.protobuf.Events.Application): ApplicationCreated = copy(application = Some(__v))
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => application.getOrElse(null)
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.zalando.komang.protobuf.Events.ApplicationCreated
}

object ApplicationCreated extends com.trueaccord.scalapb.GeneratedMessageCompanion[com.zalando.komang.protobuf.Events.ApplicationCreated] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[com.zalando.komang.protobuf.Events.ApplicationCreated] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.zalando.komang.protobuf.Events.ApplicationCreated = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.zalando.komang.protobuf.Events.ApplicationCreated(
      __fieldsMap.get(__fields.get(0)).asInstanceOf[scala.Option[com.zalando.komang.protobuf.Events.Application]]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = EventsProto.descriptor.getMessageTypes.get(1)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = {
    require(__field.getContainingType() == descriptor, "FieldDescriptor does not match message type.")
    var __out: com.trueaccord.scalapb.GeneratedMessageCompanion[_] = null
    __field.getNumber match {
      case 1 => __out = com.zalando.komang.protobuf.Events.Application
    }
  __out
  }
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.zalando.komang.protobuf.Events.ApplicationCreated(
  )
  implicit class ApplicationCreatedLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, com.zalando.komang.protobuf.Events.ApplicationCreated]) extends com.trueaccord.lenses.ObjectLens[UpperPB, com.zalando.komang.protobuf.Events.ApplicationCreated](_l) {
    def application: com.trueaccord.lenses.Lens[UpperPB, com.zalando.komang.protobuf.Events.Application] = field(_.getApplication)((c_, f_) => c_.copy(application = Some(f_)))
    def optionalApplication: com.trueaccord.lenses.Lens[UpperPB, scala.Option[com.zalando.komang.protobuf.Events.Application]] = field(_.application)((c_, f_) => c_.copy(application = f_))
  }
  final val APPLICATION_FIELD_NUMBER = 1
}
