// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.zalando.komang.protobuf.Events



object EventsProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Ch5zcmMvbWFpbi9wcm90b2J1Zi9FdmVudHMucHJvdG8SG2NvbS56YWxhbmRvLmtvbWFuZy5wcm90b2J1ZiI0CgtBcHBsaWNhd
  GlvbhIlCg5hcHBsaWNhdGlvbl9pZBgBIAEoCVINYXBwbGljYXRpb25JZCJgChJBcHBsaWNhdGlvbkNyZWF0ZWQSSgoLYXBwbGljY
  XRpb24YASABKAsyKC5jb20uemFsYW5kby5rb21hbmcucHJvdG9idWYuQXBwbGljYXRpb25SC2FwcGxpY2F0aW9uYgZwcm90bzM="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}