// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.zalando.komang.protobuf.Events



object EventsProto {
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Ch5zcmMvbWFpbi9wcm90b2J1Zi9FdmVudHMucHJvdG8SG29yZy56YWxhbmRvLmtvbWFuZy5wcm90b2J1ZiJUChdBcHBsaWNhd
  GlvbkNyZWF0ZWRFdmVudBIlCg5hcHBsaWNhdGlvbl9pZBgBIAEoCVINYXBwbGljYXRpb25JZBISCgRuYW1lGAIgASgJUgRuYW1lI
  lQKF0FwcGxpY2F0aW9uVXBkYXRlZEV2ZW50EiUKDmFwcGxpY2F0aW9uX2lkGAEgASgJUg1hcHBsaWNhdGlvbklkEhIKBG5hbWUYA
  iABKAlSBG5hbWUibwoTUHJvZmlsZUNyZWF0ZWRFdmVudBIlCg5hcHBsaWNhdGlvbl9pZBgBIAEoCVINYXBwbGljYXRpb25JZBIdC
  gpwcm9maWxlX2lkGAIgASgJUglwcm9maWxlSWQSEgoEbmFtZRgDIAEoCVIEbmFtZSJvChNQcm9maWxlVXBkYXRlZEV2ZW50EiUKD
  mFwcGxpY2F0aW9uX2lkGAEgASgJUg1hcHBsaWNhdGlvbklkEh0KCnByb2ZpbGVfaWQYAiABKAlSCXByb2ZpbGVJZBISCgRuYW1lG
  AMgASgJUgRuYW1lIo4BChJDb25maWdDcmVhdGVkRXZlbnQSHQoKcHJvZmlsZV9pZBgBIAEoCVIJcHJvZmlsZUlkEhsKCWNvbmZpZ
  19pZBgCIAEoCVIIY29uZmlnSWQSEgoEbmFtZRgDIAEoCVIEbmFtZRISCgR0eXBlGAQgASgJUgR0eXBlEhQKBXZhbHVlGAUgASgJU
  gV2YWx1ZSJoChZDb25maWdOYW1lVXBkYXRlZEV2ZW50Eh0KCnByb2ZpbGVfaWQYASABKAlSCXByb2ZpbGVJZBIbCgljb25maWdfa
  WQYAiABKAlSCGNvbmZpZ0lkEhIKBG5hbWUYAyABKAlSBG5hbWUiaAoWQ29uZmlnVHlwZVVwZGF0ZWRFdmVudBIdCgpwcm9maWxlX
  2lkGAEgASgJUglwcm9maWxlSWQSGwoJY29uZmlnX2lkGAIgASgJUghjb25maWdJZBISCgR0eXBlGAMgASgJUgR0eXBlImsKF0Nvb
  mZpZ1ZhbHVlVXBkYXRlZEV2ZW50Eh0KCnByb2ZpbGVfaWQYASABKAlSCXByb2ZpbGVJZBIbCgljb25maWdfaWQYAiABKAlSCGNvb
  mZpZ0lkEhQKBXZhbHVlGAMgASgJUgV2YWx1ZWIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}